### ISSUE TITLE
v1.1.1 doesn't start when device not present

### ISSUE THREAD

**Issue by pannal** [inoahguy02/maxwell-cutoff-fix#16]
Hey,

With the first version of the app (before the big rewrite for multiple devices), I was able to run the app on boot and it worked when "plugging in" (turning on the headset) later (as you know when the headset is off, the devices are gone).

With v1.1.1 it seems to just exit when the monitored devices aren't there.

Can you reproduce/fix that? (e.g. add an option to wait for devices, then periodically check)

Thanks!

**Comment by inoahguy02** [comment]
Nice find. Got this when adding the microphone:
```
Registering device Speakers (Game-Audeze Maxwell)
Registering device Microphone (Chat-Audeze Maxwell)
thread 'main' panicked at src\main.rs:48:69:
called `Result::unwrap()` on an `Err` value: DefaultStreamConfigError(StreamTypeNotSupported)
```
Looks like it is from this line: `let stream = OutputStream::try_from_device(&device).unwrap();`

This line was left as an unwrap because there was no point to log and it seemed impossible to throw an error right there. I think this is a cross-compatibility issue between `cpal` and `rodio`. `cpal` initializes the mic as a `Device` just fine, but when `rodio` goes to establish the connection, I'm guessing it just says it can't do anything with it, so it throws an error

Fix for now would of course be to keep the microphone out of the config. I will do more research on `rodio` to see if there's a workaround for this. If there isn't, I might just remove support for the microphone "keep-alive" since I've never had an issue with it before
