### ISSUE TITLE
Lock file stale after system crash

### ISSUE THREAD

**Issue by pannal** [inoahguy02/maxwell-cutoff-fix#22]
Pretty much what the title says. When there's a system crash, the lock file stays and the application never opens.

IMHO the application should store its current PID inside the lock file and check whether the PID inside the lock file is still running, to determine whether to run or not.

**Comment by inoahguy02** [comment]
I completely nuked the lock file and will instead look for the actual program name in the task list. Pretty much if there are more than one processes that have "maxwell-fix" in the name, then we crash. Had to rename the program to "maxwell-fix" because linux has a 15 character limit for their task list

**Comment by inoahguy02** [comment]
I was gonna go that route, but I had to dabble with unsafe winapi stuff, so I just went with the easy way. Found a crate that does global mutexes though and it is a lot faster
